[package]
name = "class07"
version = "0.1.0"
authors = ["Admin <faheemuzzaman@hotmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
text_io = "0.1.7"